### ISSUE TITLE
Similarity score thresholds

### ISSUE THREAD

**Issue by thusithathilina** [CellularLint/cellularlint-codes#4]
I've checked the TFIDF similarity scores for the Finding 1 which is on index 2014 ("From this time onward the UE shall cipher and integrity protect all NAS signalling messages with the selected NAS ciphering and NAS integrity algorithms.") using the cp_corpus_5G.txt available on the repo. The similarity scores for relevant indexes (1291, 1294, 1298, 1336) (all segments that contains 'From this time onward, all NAS messages exchanged be' part) are well below 0.5.
Did you do any further preprocessing to get the filtered out dataset that was used for the inference with the LLM model?

**Comment by Masfiqur-Mim** [comment]
Hi @thusithathilina,
Thank you for raising the discussion. Can you please check the pairs 1291 and 1298? The similarity value should be 0.72
We did not do additional preprocessing at this step.

**Comment by thusithathilina** [comment]
@Masfiqur-Mim thanks for the info. I've checked the segments in 1291 and 1298 listed below (in 5G context)

---------------------------------------------------------
1291 - 

> After the AMF receives the REGISTRATION REQUEST message 1) if the AMF decides to take the native 5G NAS security context into use, the security mode control procedure is performed.
> From this time onward, all NAS messages exchanged between the UE and the AMF are sent integrity protected using the native 5G NAS security context, and except for the messages specified in subclause4.4.5, all NAS messages exchanged between the UE and the AMF are sent ciphered using the native 5G NAS security context; or 2) if the AMF decides to take the mapped 5G NAS security context into use, **from this time onward, all NAS messages exchanged between the UE and the AMF are sent integrity protected using the mapped 5G NAS security context, and except for the messages specified in subclause4.4.5,** all NAS messages exchanged between the UE and the AMF are sent ciphered using the mapped 5G NAS security context During inter-system change from S1 mode to N1 mode in 5GMM-IDLE mode, if the UE is operating in single-registration mode and a) if the UE has a valid native 5G NAS security context, the UE shall transmit a REGISTRATION REQUEST message integrity protected with the native 5G NAS security context.

1298 - 

> If the verification is successful, the AMF may re-establish the secure exchange of NAS messages a) by replying with a NAS message that is integrity protected and ciphered using the current 5G NAS security context.
> **From this time onward, all NAS messages exchanged between the UE and the AMF are sent integrity protected and except for the messages specified in subclause 4.4.5**, all NAS messages exchanged between the UE and the AMF are sent ciphered; or b) by initiating a security mode control procedure.
> 

As you mentioned the similarity score is ~0.7234. 
However, as I understand, both of these segments are entail with each other as they include that exception clause. 
The one that doesn't include the exception clause is in index 2014

> The UE shall set the security header type of the message to "integrity protected and ciphered with new 5G NAS security context" **From this time onward the UE shall cipher and integrity protect all NAS signalling messages with the selected 5GS integrity and ciphering algorithms** If the AMF indicated in the SECURITY MODE COMMAND message that the IMEISV is requested and a) if the UE 1) supports at least one 3GPP access technology, the UE shall include its IMEISV in the IMEISV IE of the SECURITY MODE COMPLETE message; or 2) does not support any 3GPP access technology 

So shouldn't we check the similarity score against 2014? where scores are as follows 
2014 vs 1291 = 0.3819450513371713
2014 vs 1298 = 0.3528217466674845

In 4G context
As I understand relevant indexes are 1117 and (762, 764, 767, 770, 772, 776) \

> The UE shall set the security header type of the message to "integrity protected and ciphered with new EPS security context" **From this time onward the UE shall cipher and integrity protect all NAS signalling messages with the selected NAS ciphering and NAS integrity algorithms** If the MME indicated in the SECURITY MODE COMMAND message that the IMEISV is requested, the UE shall include its IMEISV in the SECURITY MODE COMPLETE message In WB-S1 mode, if the MME indicated in the SECURITY MODE COMMAND message that the UE radio capability ID is requested, the UE shall if the UE has an applicable network-assigned UE radio capability ID for the current UE radio configuration in the selected PLMN, include the applicable network-assigned UE radio capability ID in the UE radio capability ID IE of the SECURITY MODE COMPLETE message; and if the UE a) does not have an applicable network-assigned UE radio capability ID for the current UE radio configuration in the selected PLMN; and b) has an applicable manufacturer-assigned UE radio capability ID for the current UE radio configuration include the applicable manufacturer-assigned UE radio capability ID in the UE radio capability ID IE of the SECURITY MODE COMPLETE message If, during an ongoing attach or tracking area updating procedure, the SECURITY MODE COMMAND message includes a HASHMME, the UE shall compare HASHMME with a hash value locally calculated as described in 3GPP S 33.401 [19] from the entire plain ATTACH REQUEST or TRACKING AREA UPDATE REQUEST message that the UE had sent to initiate the procedure.

> The UE uses these parameters to generate the mapped EPS security context; and after the handover, the transmission of a TRACKING AREA UPDATE REQUEST message from the UE to the MME.
> The UE shall send this message integrity protected using the mapped EPS security context, but unciphered.
> **From this time onward, all NAS messages exchanged between the UE and the MME are sent integrity protected using the mapped EPS security context, and except for the messages specified in clause 4.4.5**, all NAS messages exchanged between the UE and the MME are sent ciphered using the mapped EPS security context During inter-system change from N1 mode to S1 mode in EMM-CONNECTED mode, secure exchange of NAS messages is established between the MME and the UE by the transmission of NAS security related parameters encapsulated in the AS signalling from the AMF to the UE triggering the inter-system handover (see 3GPP S 33.501 [56]).

> **From this time onward, all NAS messages exchanged between the UE and the MME are sent integrity protected using the mapped EPS security context, and except for the messages specified in clause 4.4.5,** all NAS messages exchanged between the UE and the MME are sent ciphered using the mapped EPS security context During inter-system change from N1 mode to S1 mode in EMM-IDLE mode, if the UE is operating in the single-registration mode and 1) if the tracking area updating procedure is initiated as specified in 3GPP S 24.501 [54], the UE shall transmit a TRACKING AREA UPDATE REQUEST message integrity protected with the current 5G NAS security context and the UE shall derive a mapped EPS security context (see clause 8.6.1 of 3GPP S 33.501 [56]).


> **From this time onward, all NAS messages exchanged between the UE and the MME are sent integrity protected and except for the messages specified in clause 4.4.5**, all NAS messages exchanged between the UE and the MME are sent ciphered; or initiating a security mode control procedure.
> This can be used by the MME to take a non-current EPS security context into use or to modify the current EPS security context by selecting new NAS security algorithms; or 2) if the attach procedure is initiated as specified in 3GPP S 24.501 [54] and a) if the UE has received an "interworking without N26 interface not supported" indication from the network and the UE has a valid 5G NAS security context, the UE shall send an ATTACH REQUEST message integrity protected with the current 5G NAS security context and the UE shall derive a mapped EPS security context (see clause 8.6.1 of 3GPP S 33.501 [56]).


> **From this time onward, all NAS messages exchanged between the UE and the MME are sent integrity protected and except for the messages specified in clause 4.4.5,** all NAS messages exchanged between the UE and the MME are sent ciphered; or initiating a security mode control procedure.
> This can be used by the MME to modify the current EPS security context by selecting new NAS security algorithms; or i) if the UE has a valid native EPS security context, the UE shall send an ATTACH REQUEST message integrity protected with the native EPS security context.

> If the verification is successful, the MME re-establishes the secure exchange of NAS messages by either replying with an ATTACH ACCEPT message that is integrity protected and ciphered using the current EPS security context.
> **From this time onward, all NAS messages exchanged between the UE and the MME are sent integrity protected and except for the messages specified in clause 4.4.5,** all NAS messages exchanged between the UE and the MME are sent ciphered; or initiating a security mode control procedure.

> **From this time onward, all NAS messages exchanged between the UE and the MME are sent integrity protected and except for the messages specified in clause 4.4.5,** all NAS messages exchanged between the UE and the MME are sent ciphered; or by initiating a security mode control procedure.
> This can be used by the MME to take a non-current EPS security context into use or to modify the current EPS security context by selecting new NAS security algorithms; or 2) If the initial NAS message was a SERVICE REQUEST message or EXTENDED SERVICE REQUEST message, secure exchange of NAS messages is triggered by the indication from the lower layers that the user plane radio bearers are successfully set up.

Similarity scores are as follows 
1117 vs 762 = 0.2587876564207077
1117 vs 764 = 0.2877732853902644
1117 vs 767 = 0.30150405736179225
1117 vs 770 = 0.289142382589198
1117 vs 772 = 0.21482072741697553
1117 vs 776 = 0.29147631732843643

Did I miss anything?

**Comment by Masfiqur-Mim** [comment]
Hello @thusithathilina,
Even though the pair with the different clause falls below the threshold (unlike the other pair of "similar" discussions above the threshold), this specific issue was the key motivation from the very beginning of our design; thus, we included it in the set of training examples. Specifically, a closely related inconsistency was pointed out in a previous work [[1]](https://syed-rafiul-hussain.github.io/wp-content/uploads/2021/09/dikeue.pdf), which helped us to trace back to it as a positive sample, even though the threshold was prohibitive for it (in fact, there was a bit of tweaking for an appropriate threshold as you may have noticed from the paper discussion). Note that without such a concrete example as ground truth, it was difficult to determine if a consistency measure can indeed be employed. Therefore, we had to keep it notwithstanding the $\psi$ value. However, the thresholding is indeed useful in other scenarios. For instance, the findings shown in the paper-

Finding 2: (from 4G)
1199-
> The UE shall consider the USIM as invalid for EPS services and non-EPS services until switching off or the UICC containing the USIM is removed or the timer T3245 expires as described in clause 5.3.7a. Additionally, the UE shall delete the list of equivalent PLMNs and enter state EMM-DEREGISTERED.NO-IMSI. If the message has been successfully integrity checked by the NAS and the UE maintains a counter for "SIM/USIM considered invalid for GPRS services", then the UE shall set this counter to UE implementation-specific maximum value.

1340-

> The UE shall consider the USIM as invalid for EPS services until switching off or the UICC containing the USIM is removed or the timer T3245 expires as described in clause 5.3.7a. The UE shall delete the list of equivalent PLMNs and shall enter the state EMM-DEREGISTERED.NO-IMSI. If the UE maintains a counter for "SIM/USIM considered invalid for GPRS services", then the UE shall set this counter to UE implementation-specific maximum value.

Similarity: ~0.94

Finding 3: (from 4G)
259-
> In case of failed integrity check (i.e. faulty or missing MAC-I) is detected after the start of integrity protection, the concerned message shall be discarded. This can happen on the UE side or on the eNB side.

316
> In case of failed integrity check (i.e. faulty or missing NAS-MAC) is detected after the start of NAS integrity protection the concerned message shall be discarded except for some NAS messages specified in TS 24.301 [9]. For those exceptions the MME shall take the actions specified in TS 24.301 [9] when receiving a NAS message with faulty or missing NAS-MAC.

Similarity: 0.67

Finding 4: (from 5G)
366-
> If this verification is successful, then the UE shall take the received NCC value and save it as stored NCC with the current UE context. The UE shall delete the current AS keys KRRCenc, KUPenc (if available), and KUPint (if available), but keep the current AS key KRRCint key. If the stored NCC value is different from the NCC value associated with the current KgNB, the UE shall delete the current AS key KgNB.

598-
> If the sent NCC value is fresh and belongs to an unused pair of {NCC, NH}, the ng-eNB shall save the pair of {NCC, NH} in the current UE AS security context and shall delete the current AS key KgNB. If the sent NCC value is equal to the NCC value associated with the current KgNB, the ng-eNB shall keep the current AS key KgNB and NCC.

Similarity: ~0.7

Finding 5: (from 5G)
2248-
> If the REGISTRATION REJECT is not integrity protected, the UE shall memorize the current TAI was stored in the list of "5GS forbidden tracking areas for regional provision of service" for the current SNPN and, if the UE supports access to an SNPN using credentials from a credentials holder, the selected entry of the "list of subscriber data" or the selected PLMN subscription, for non-integrity protected NAS reject message If the message was received via 3GPP access and the UE is operating in single-registration mode, the UE shall handle the EMM parameters EMM state, EPS update status, 4G-GUTI, last visited registered TAI, TAI list, eKSI and attach attempt counter as specified in 3GPPTS24.301[15] for the case when the EPS attach request procedure is rejected with the EMM cause with the same value #13 (Roaming not allowed in this tracking area) The UE shall set the 5GS update status to 5U3 ROAMING NOT ALLOWED (and shall store it according to subclause5.1.3.2.2) and shall delete 5G-GUTI, last visited registered TAI, TAI list and ngKSI.

2462-
> If the REGISTRATION REJECT message is not integrity protected, the UE shall memorize the current TAI was stored in the list of "5GS forbidden tracking areas for regional provision of service" for the current SNPN and, if the UE supports access to an SNPN using credentials from a credentials holder, the selected entry of the "list of subscriber data" or the selected PLMN subscription, for non-integrity protected NAS reject message If the message was received via 3GPP access and the UE is operating in single-registration mode, the UE shall handle the EMM parameters EMM state, EPS update status, 4G-GUTI, last visited registered TAI, TAI list, eKSI and tracking area updating attempt counter as specified in 3GPPTS24.301[15] for the case when the normal tracking area updating procedure is rejected with the EMM cause with the same value #13 (Roaming not allowed in this tracking area) The UE shall set the 5GS update status to 5U3 ROAMING NOT ALLOWED (and shall store it according to subclause5.1.3.2.2) and shall delete the list of equivalent PLMNs (if available).

Similarity: ~0.89

Finding 6: (from 4G)
1505-
> If the DETACH REQUEST message contains detach type "re-attach not required" and EMM cause #2 "IMSI unknown in HSS", the UE will follow the procedure as described below for the detach type "IMSI detach" EPS detach containing detach type "IMSI detach" If the UE receives a DETACH REQUEST message before the tracking area updating procedure has been completed, the DETACH REQUEST message shall be ignored and tracking area updating procedure shall be progressed The UE shall proceed as described below g) Tracking area updating and GUTI reallocation procedure collision If the UE receives a GUTI REALLOCATION COMMAND message before the tracking area updating procedure has been completed, this message shall be ignored and the tracking area updating procedure shall be progressed h) Transmission failure of TRACKING AREA UPDATE REQUEST message indication from lower layers The tracking area updating procedure shall be aborted and re-initiated immediately.

1524-
> If a failure of the handover procedure is reported by the lower layer and the S1 signalling connection exists, the MME shall retransmit the TRACKING AREA UPDATE ACCEPT message or TRACKING AREA UPDATE REJECT message g) DETACH REQUEST message received before the TRACKING AREA UPDATE ACCEPT message is sent or before the TRACKING AREA UPDATE COMPLETE message (in case of GUTI and/or TMSI was allocated) is received Detach containing cause "switch off" The network shall abort the signalling for the tracking area updating procedure towards the UE and shall progress the detach procedure as described in clause 5.5.2.2 NOTE 4: Internally in the network, before processing the detach request, the MME can perform the necessary signalling procedures for the tracking area updating procedure before progressing the detach procedure Detach containing other causes than "switch off" The network shall proceed with the tracking area updating procedure and shall progress the detach procedure after successful completion of the tracking area updating procedure h) If the TRACKING AREA UPDATE REQUEST message with EPS update type IE indicating "periodic updating" is received by the new MME which does not have the EMM context data related to the subscription, the new MME may send the TRACKING AREA UPDATE REJECT message with EMM cause value #10 "Implicitly detached" .

Similarity: ~0.67
and so on. I hope this clarifies.

**Comment by thusithathilina** [comment]
@Masfiqur-Mim Thank you very much for the explanation 👍
